# Generated by Django 4.2.7 on 2024-01-12 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Function",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("function", models.CharField(max_length=50, unique=True)),
                ("description", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40, unique=True)),
                ("description", models.CharField(max_length=100)),
                ("kindOf", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("error", "Error"),
                            ("warning", "Warning"),
                            ("notification", "Notification"),
                        ]
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("message", models.TextField()),
                ("description", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Microcontroller",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("ip", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=40)),
                ("lastname", models.CharField(max_length=40)),
                ("email", models.CharField(max_length=50, unique=True)),
                ("password", models.CharField(max_length=50)),
                ("key", models.CharField(max_length=50, unique=True)),
                (
                    "gender",
                    models.TextField(
                        blank=True,
                        choices=[
                            ("männlich", "Männlich"),
                            ("weiblich", "Weiblich"),
                            ("divers", "Divers"),
                        ],
                        null=True,
                    ),
                ),
                ("birthdate", models.DateField(blank=True, max_length=50, null=True)),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user",
                        to="e_paul_smarthome_system.group",
                        verbose_name="Group",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Scene",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("startTime", models.DateTimeField()),
                ("endTime", models.DateTimeField()),
                (
                    "description",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "function",
                    models.ManyToManyField(to="e_paul_smarthome_system.function"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "art",
                    models.CharField(
                        choices=[("Eingang", "Eingang"), ("Ausgang", "Ausgang")],
                        max_length=50,
                    ),
                ),
                ("inUse", models.BooleanField(default=False)),
                (
                    "microcontroller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="e_paul_smarthome_system.microcontroller",
                        verbose_name="Microcontroller",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="microcontroller",
            name="User",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="microcontroller",
                to="e_paul_smarthome_system.user",
                verbose_name="User",
            ),
        ),
        migrations.AddField(
            model_name="function",
            name="microcontroller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="e_paul_smarthome_system.microcontroller",
                verbose_name="Microcontroller",
            ),
        ),
    ]
