# Generated by Django 4.2.7 on 2023-11-19 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mikrocontroller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ip', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(max_length=40)),
                ('nachname', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('passwort', models.CharField(max_length=50)),
                ('key', models.CharField(max_length=50, unique=True)),
                ('geschlecht', models.TextField(choices=[('männlich', 'Männlich'), ('weiblich', 'Weiblich'), ('divers', 'Divers')])),
                ('geburtsdatum', models.DateField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.CharField(choices=[('Eingang', 'Eingang'), ('Ausgang', 'Ausgang')], max_length=50)),
                ('used', models.BooleanField(default=False)),
                ('mikrocontroller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_paul_smarthome_system.mikrocontroller', verbose_name='Pin')),
            ],
        ),
        migrations.AddField(
            model_name='mikrocontroller',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_paul_smarthome_system.user', verbose_name='Mikrocontroller'),
        ),
        migrations.CreateModel(
            name='Gruppe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('beschreibung', models.CharField(max_length=100)),
                ('art', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_paul_smarthome_system.user', verbose_name='Gruppe')),
            ],
        ),
        migrations.CreateModel(
            name='Funktion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funktion', models.CharField(max_length=50, unique=True)),
                ('beschreibung', models.CharField(max_length=100)),
                ('mikrocontroller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_paul_smarthome_system.mikrocontroller', verbose_name='Funktion')),
            ],
        ),
    ]
