# Generated by Django 4.2.7 on 2024-02-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("e_paul_smarthome_system", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="firstname",
        ),
        migrations.RemoveField(
            model_name="account",
            name="lastname",
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.TextField(
                choices=[
                    ("superuser", "Superuser"),
                    ("admin", "Admin"),
                    ("user", "User"),
                ]
            ),
        ),
    ]
