# Generated by Django 4.2.7 on 2024-03-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_paul_smarthome_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='emailVerified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='key',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='groupType',
            field=models.TextField(blank=True, choices=[('Standard', 'Standard'), ('Favorite', 'Favorite'), ('Assignment', 'Assignment')], default='Standard', null=True),
        ),
        migrations.DeleteModel(
            name='Function',
        ),
    ]
