# Generated by Django 4.2.7 on 2024-02-21 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("e_paul_smarthome_system", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="microcontroller",
            old_name="User",
            new_name="account",
        ),
    ]
