# Generated by Django 4.2.7 on 2024-03-18 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_paul_smarthome_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='porttemplate',
            name='knownControllerType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portTemplate', to='e_paul_smarthome_system.knowncontrollertype', verbose_name='Microcontroller'),
        ),
    ]
