# Generated by Django 4.2.7 on 2024-02-20 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_paul_smarthome_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='microcontroller',
            name='ip',
        ),
    ]
