# Generated by Django 4.2.7 on 2024-01-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_paul_smarthome_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pin',
            field=models.CharField(max_length=100),
        ),
    ]
