# Generated by Django 5.0.1 on 2024-02-08 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_paul_smarthome_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pictureid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
