# Generated by Django 4.2.7 on 2023-11-19 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_paul_smarthome_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funktion',
            name='mikrocontroller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_paul_smarthome_system.mikrocontroller', verbose_name='Mikrocontroller'),
        ),
        migrations.AlterField(
            model_name='gruppe',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_paul_smarthome_system.user', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='mikrocontroller',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_paul_smarthome_system.user', verbose_name='User'),
        ),
    ]
