# Generated by Django 4.2.7 on 2024-03-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_paul_smarthome_system', '0002_porttemplate_knowncontrollertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandoption',
            name='value',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Value'),
        ),
    ]
