# Generated by Django 4.2.7 on 2024-03-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_paul_smarthome_system', '0002_account_emailverified_account_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='microcontroller',
            name='type',
            field=models.CharField(default='ESP8266', max_length=32),
        ),
        migrations.AlterField(
            model_name='account',
            name='key',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='microcontroller',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
