# Generated by Django 4.2.7 on 2023-11-22 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "e_paul_smarthome_system",
            "0002_alter_funktion_mikrocontroller_alter_gruppe_user_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="pin",
            name="mikrocontroller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="e_paul_smarthome_system.mikrocontroller",
                verbose_name="Mikrocontroller",
            ),
        ),
    ]
