# Generated by Django 5.0.2 on 2024-02-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_paul_smarthome_system', '0002_user_pictureid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pictureid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
