# Generated by Django 4.2.7 on 2024-02-23 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_paul_smarthome_system', '0002_rename_user_microcontroller_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microcontroller',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='microcontroller', to='e_paul_smarthome_system.account', verbose_name='Account'),
        ),
    ]
