# Generated by Django 4.2.7 on 2024-03-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_paul_smarthome_system', '0003_microcontroller_type_alter_account_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='port',
            name='art',
        ),
        migrations.AddField(
            model_name='port',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
