# Generated by Django 4.2.7 on 2023-12-01 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("e_paul_smarthome_system", "0003_alter_user_group"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pin",
            old_name="mikrocontroller",
            new_name="microcontroller",
        ),
        migrations.AlterField(
            model_name="user",
            name="birthdate",
            field=models.DateField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.TextField(
                blank=True,
                choices=[
                    ("männlich", "Männlich"),
                    ("weiblich", "Weiblich"),
                    ("divers", "Divers"),
                ],
                null=True,
            ),
        ),
    ]
