# Generated by Django 4.2.7 on 2024-03-08 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_paul_smarthome_system', '0004_remove_port_art_port_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='microcontroller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='port', to='e_paul_smarthome_system.microcontroller', verbose_name='Microcontroller'),
        ),
    ]
