# Generated by Django 4.2.7 on 2023-12-01 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "e_paul_smarthome_system",
            "0004_rename_mikrocontroller_pin_microcontroller_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="pin",
            old_name="used",
            new_name="inUse",
        ),
    ]
