# Generated by Django 4.2.7 on 2024-03-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_paul_smarthome_system', '0004_remove_command_type_command_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
