# Generated by Django 4.2.7 on 2024-03-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_paul_smarthome_system', '0005_alter_port_microcontroller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='port',
            name='inUse',
        ),
        migrations.AddField(
            model_name='port',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='port',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
