# Generated by Django 4.2.7 on 2024-03-09 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_paul_smarthome_system', '0006_remove_port_inuse_port_name_alter_port_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
